export const actionTypes = {
    FETCH_BOOK_LIST: 'FETCH_BOOK_LIST',
    ADD_BOOK_TO_LIBRARY: 'ADD_BOOK_TO_LIBRARY',
    FETCH_BOOK_LIST_SUCCESS: 'FETCH_BOOK_LIST_SUCCESS',
    UPDATE_BOOK_DETAILS: 'UPDATE_BOOK_DETAILS',
    UPDATE_SEARCH_RESULT: 'UPDATE_SEARCH_RESULT'
}